//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentManagementEntities : DbContext
    {
        public StudentManagementEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ExamResult> ExamResults { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
    
        public virtual ObjectResult<GetAllSearchInfo_Result> GetAllSearchInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllSearchInfo_Result>("GetAllSearchInfo");
        }
    
        public virtual ObjectResult<GetStudentsByClassName_Result> GetStudentsByClassName(string className)
        {
            var classNameParameter = className != null ?
                new ObjectParameter("ClassName", className) :
                new ObjectParameter("ClassName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentsByClassName_Result>("GetStudentsByClassName", classNameParameter);
        }
    
        public virtual ObjectResult<GetStudentsByStudentName_Result> GetStudentsByStudentName(string studentName)
        {
            var studentNameParameter = studentName != null ?
                new ObjectParameter("StudentName", studentName) :
                new ObjectParameter("StudentName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentsByStudentName_Result>("GetStudentsByStudentName", studentNameParameter);
        }
    
        public virtual ObjectResult<GetStudentsInfoByRating_Result> GetStudentsInfoByRating(string rating)
        {
            var ratingParameter = rating != null ?
                new ObjectParameter("Rating", rating) :
                new ObjectParameter("Rating", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentsInfoByRating_Result>("GetStudentsInfoByRating", ratingParameter);
        }
    
        public virtual ObjectResult<GetStudentsTop10_Result> GetStudentsTop10()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentsTop10_Result>("GetStudentsTop10");
        }
    }
}
